# Site settings
title: Prashant Padmanabhan
email: prashant.pro@gmail.com
description: One mans thoughts and learnings for another.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.prashantp.org"
# twitter_username: jekyllrb
github_username:  prashantpro
#permalink: /:year/:month/:day/:title/
permalink: pretty

disqus_shortname: prashantporg
disqus_url: "http://www.prashantp.org"

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]

paginate: 10
paginate_path: "page:num"

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
