version: '2'
services:
  web:
    image: jekyll/jekyll:pages
    #command: jekyll s --force_polling --drafts
    command: jekyll serve --watch --incremental
    ports:
     - "4000:4000"
    volumes:
     - .:/srv/jekyll

